### ISSUE TITLE
能否自带手势？

### ISSUE THREAD

**Issue by bao3** [esterTion/ReplayKitEverywhere#1]
主要缘由：
1. Activator 比较大，也不想装。
2. Activator 的更新经常落后于越狱进度，相当一段时间会用了这个手势
3. Audiorecorder 就自带了双击顶 栏手势，这样就非常方便。
我想自带手势也许难度比较大，但仍然请考虑添加。

**Comment by esterTion** [comment]
自带手势一个是我完全不清楚怎么识别，另一个是，事实上iOS内部已经有了太多手势（比如双击顶栏明显会导致内容回到顶部的副作用）。activator不仅是有更多选择，同时还可以覆盖系统手势。
落后进度的话就只有10.3了，这个我也没什么办法只能等（我自己是个重度activator用户），测试版可以加[beta源](https://rpetri.ch/repo/)，虽然目前也没有动静

**Comment by bao3** [comment]
1. 手势识别，我也不懂。。。
2. AudioRecorder 不止是双击，也有滑动顶栏的动作，这些动作是可以开关的，也同样是覆盖了系统的手势的。好处就是主程序一更新，这些手势直接可以用，体验一致。
3. Activator 因为体量大，更新要考虑的东西太多，所以在 11.1.2 上基本上要等个半年才能用。
4. 我倒是建议是不是可以解锁手势作为一个 IAP，既不影响既有体验，又可以为其他人提供便利和更好的体验

**Comment by esterTion** [comment]
不计划支持iOS11，所以不考虑那个的问题
主要是懒（被打）
程序员本质就是偷懒复用别人的代码/库（暴言）

我自己用法是有个按住电源键的弹出菜单，在里面放的选项
