### ISSUE TITLE
New logo / icon

### ISSUE THREAD

**Issue by mansya** [esterTion/ReplayKitEverywhere#2]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by esterTion** [comment]
Thanks for your interest of helping! 
I'm currently using Apple's official icon for this tweak, and I think it's good enough. 
![](replaykiteverywhereprefs/Resources/Icon@3x.png)

**Comment by esterTion** [comment]
Oops, wrong image linked. 
![](https://github.com/esterTion/ReplayKitEverywhere/blob/master/replaykiteverywhereprefs/Resources/Icon@3x.png?raw=true)
